### ISSUE TITLE
Is this lib still maintained?

### ISSUE THREAD

**Issue by Rainer-Lang** [michael-rapp/AndroidMaterialPreferences#4]

**Comment by michael-rapp** [comment]
Yes, it is. Why? Are there any issues with it?

**Comment by Rainer-Lang** [comment]
Just wanted to know, because the last commit is about a month old.
Do you plan to integrate a "image"-preference?

And how can I integrate saving in a database? Where would be the right place to do it?

**Comment by michael-rapp** [comment]
The library is quite stable. There is no need to change things unless new functionality should be added.

An image preference would be a little different from all other preferences, which are provided by the library, because images are usually stored as files instead of shared preference values. Therefore I had no plans to implement such a thing so far.

Why would you want to store the value of a preference in a database? By default it is automatically stored in the shared preferences and can be globally retrieved without much effort. Storing and retrieving values in a database requires much more code. Nevertheless, you can add a `OnPreferenceChangeListener` to each preference by using its `setOnPreferenceChangeListener`-method. The listener is called each time the value of the preference is changed. So it would be possible to update the database when the listener is called. But implementing this would cause the value to be stored twice - in the database as well as in the shared preferences. I strongly discourage from this approach.

**Comment by michael-rapp** [comment]
If you really want an image preference, you can open another issue so we can discuss it. Please describe what kind of functionality you would expect and how it should behave and look like. Thank you.

**Comment by Rainer-Lang** [comment]
1) store in database:
I need this because my database is synced with a webserver. The settings are stored in a table of the db and are synced like all other stuff (tables) in the db. I think ```OnPreferenceChangeListener``` will do it. Thanks.

2) "image"-preference:
https://github.com/michael-rapp/AndroidMaterialPreferences/issues/5
