### ISSUE TITLE
image-preference

### ISSUE THREAD

**Issue by Rainer-Lang** [michael-rapp/AndroidMaterialPreferences#5]
In the settings the user should be able to set a profile image. This image should be visible in the settings-view.

**Comment by michael-rapp** [comment]
I guess it should be possible to select an image from the gallery as well as to capture an image using the camera, right? This will cause a dialog to be shown, which allows to select, what app should be used to select/capture the image. It is not necessary to open another dialog beforehand, which shows the current image and allows to delete it, is it?

Because it is not recommended to store image data in shared preferences, only the path to image files will be stored. The images themselves will stored on the device's storage instead. I guess it would be best to use the app's private directory. When choosing an image from an other location the file will be copied into the private directory. This prevents the image from getting lost when it is deleted by an other app.

**Comment by Rainer-Lang** [comment]
I describe the workflow (for me):
1) User selects image (gallery/camera)
2) crop image (with https://github.com/IsseiAoki/SimpleCropView)
3) save the image in private app folder + save the path to image in preference + show thumbnail in settings-view

**Comment by michael-rapp** [comment]
Alright, if cropping is required, this adds additional complexity and an additional dialog has to be shown. I will think about this.

**Comment by Rainer-Lang** [comment]
see here: https://github.com/michael-rapp/AndroidMaterialPreferences/issues/7

**Comment by michael-rapp** [comment]
I thought about this issue in a more detailed way and I realized, that implementing this preference would require to deal with issues which go far beyond the scope of all other preferences, which are already provided by the library. For example, it would be necessary to cope with error handling (e.g. what happens if the gallery app can not be opened or if copying files fails). Furthermore, I can imagine very different use cases for picking images and I don't think it is possible to fit all needs with one implementation. Therefore I decided to not implement such a preference because I want to keep the library simple (it only provides simple views instead of implementing complex use cases) and because I don't have enough time to deal with all the issues in a detailed way at the moment. I am sorry!
