### ISSUE TITLE
Possible to include other pickers - like Date/TimePicker?

### ISSUE THREAD

**Issue by Rainer-Lang** [michael-rapp/AndroidMaterialPreferences#7]
Maybe possible to open other pickers from other libs to get values?
This would be really awesome. :-)

**Comment by michael-rapp** [comment]
In fact this is already possible, although no generic interface is provided. This isn't really possible anyway, because third-party library's widely differ in their APIs. But you can extend the class `AbstractDialogPreference`, if you want to show any `View` in a dialog. If the library provides its own dialogs, you have to extend Android's `Preference` class instead. Of course this requires some programming effort, but I can assist you, if you have any questions.
